# Generated by Django 4.1.7 on 2023-08-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embed', models.TextField(verbose_name='Код для вставки')),
                ('key', models.CharField(max_length=128, verbose_name='Ключ для подключения')),
            ],
        ),
    ]
