# Generated by Django 3.2 on 2023-03-04 19:23

import course.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('time_limit', models.IntegerField(default=1, validators=[course.validators.validate_more_zero], verbose_name='Ограничение времени (секунд)')),
                ('memory_limit', models.IntegerField(default=64, validators=[course.validators.validate_more_zero], verbose_name='Ограничение памяти (Mb)')),
                ('text', models.TextField(verbose_name='Текст задания')),
                ('input_type', models.CharField(default='стандартный ввод или input.txt', max_length=100, verbose_name='Ввод')),
                ('output_type', models.CharField(default='стандартный вывод или output.txt', max_length=100, verbose_name='Вывод')),
                ('input_format', models.TextField(blank=True, null=True, verbose_name='Формат ввода')),
                ('output_format', models.TextField(blank=True, null=True, verbose_name='Формат вывода')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(blank=True, null=True, verbose_name='Ввод')),
                ('output_data', models.TextField(blank=True, null=True, verbose_name='Вывод')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.task', verbose_name='Задание')),
            ],
            options={
                'verbose_name': 'Пример',
                'verbose_name_plural': 'Примеры',
            },
        ),
    ]
