# Generated by Django 3.2 on 2023-03-04 21:06

import course.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('theory', models.TextField(verbose_name='Теория')),
            ],
        ),
        migrations.AlterModelOptions(
            name='example',
            options={'verbose_name': 'пример', 'verbose_name_plural': 'примеры'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'задание', 'verbose_name_plural': 'задания'},
        ),
        migrations.AddField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***')], default=1, verbose_name='Сложность задания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='memory_limit',
            field=models.IntegerField(default=64, help_text='(Mb)', validators=[course.validators.validate_more_zero], verbose_name='Ограничение памяти'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_limit',
            field=models.IntegerField(default=1, help_text='(секунд)', validators=[course.validators.validate_more_zero], verbose_name='Ограничение времени'),
        ),
        migrations.AddField(
            model_name='task',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.lesson', verbose_name='Урок'),
        ),
    ]
