# Generated by Django 3.2 on 2023-03-04 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20230304_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='Название')),
                ('entry', models.TextField(verbose_name='Вступление')),
            ],
            options={
                'verbose_name': 'курс',
                'verbose_name_plural': 'курс',
            },
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'курс', 'verbose_name_plural': 'курсы'},
        ),
        migrations.AlterField(
            model_name='example',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.task', verbose_name='Задание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='difficulty',
            field=models.IntegerField(choices=[(1, '*'), (2, '**'), (3, '***')], default=1, verbose_name='Сложность'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='Курс'),
        ),
    ]
