# Generated by Django 3.2 on 2023-03-04 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20230304_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'verbose_name': 'урок', 'verbose_name_plural': 'уроки'},
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty',
            field=models.IntegerField(choices=[(1, 'Начинающий'), (2, 'Продвинутый'), (3, 'Профессионал')], default=1, verbose_name='Сложность'),
        ),
    ]
