# Generated by Django 3.2 on 2023-03-04 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20230304_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='difficulty',
            field=models.CharField(choices=[('Начинающий', 'Начинающий'), ('Продвинутый', 'Продвинутый'), ('Профессионал', 'Профессионал')], default='Начинающий', max_length=20, verbose_name='Сложность'),
        ),
    ]
