# Generated by Django 3.2 on 2023-03-05 10:27

from django.db import migrations
import django.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_is_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='entry',
            field=django.db.models.TextField(verbose_name='Вступление'),
        ),
    ]
