# Generated by Django 3.2 on 2023-03-05 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_alter_course_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='entry',
            new_name='introduction',
        ),
        migrations.AddField(
            model_name='course',
            name='lead',
            field=models.CharField(default=1, max_length=250, verbose_name='Лид'),
            preserve_default=False,
        ),
    ]
