# Generated by Django 4.1.7 on 2023-03-11 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_auto_20230305_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='text_color',
        ),
    ]
