# Generated by Django 4.1.7 on 2023-05-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_task_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='solution',
            field=models.TextField(blank=True, default='<pre class="language-python">&nbsp;</pre>', null=True, verbose_name='Решение автора'),
        ),
    ]
