# Generated by Django 4.1.7 on 2023-05-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_task_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='input_format',
            field=models.TextField(blank=True, default='', verbose_name='Формат ввода'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='output_format',
            field=models.TextField(blank=True, default=1, verbose_name='Формат вывода'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='solution',
            field=models.TextField(blank=True, default='<pre class="language-python">&nbsp;</pre>', verbose_name='Решение автора'),
        ),
    ]
