# Generated by Django 4.1.7 on 2023-07-31 15:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0019_alter_task_input_format_alter_task_output_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Пользователи с доступом к курсу'),
        ),
        migrations.AddField(
            model_name='course',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Сделать курс приватным'),
        ),
    ]
