# Generated by Django 4.1.7 on 2023-07-31 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_privatematerial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatematerial',
            old_name='introduction',
            new_name='text',
        ),
    ]
